// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsYmVa2Bh0H5kA3Zf7tAqhyZ69II7j1go',
    appId: '1:1019228006325:web:4a756a64d403670c9d9bfc',
    messagingSenderId: '1019228006325',
    projectId: 'temu-recipe',
    authDomain: 'temu-recipe.firebaseapp.com',
    storageBucket: 'temu-recipe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhEu188xY2IbOEnZrDeoY8HqC1tuGcmKY',
    appId: '1:1019228006325:android:19efccbd56d406ef9d9bfc',
    messagingSenderId: '1019228006325',
    projectId: 'temu-recipe',
    storageBucket: 'temu-recipe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0b3odAenJPfdCFsbT9LHEU7EWeHaf4xw',
    appId: '1:1019228006325:ios:413e78993341724a9d9bfc',
    messagingSenderId: '1019228006325',
    projectId: 'temu-recipe',
    storageBucket: 'temu-recipe.firebasestorage.app',
    iosBundleId: 'com.example.temuRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0b3odAenJPfdCFsbT9LHEU7EWeHaf4xw',
    appId: '1:1019228006325:ios:413e78993341724a9d9bfc',
    messagingSenderId: '1019228006325',
    projectId: 'temu-recipe',
    storageBucket: 'temu-recipe.firebasestorage.app',
    iosBundleId: 'com.example.temuRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsYmVa2Bh0H5kA3Zf7tAqhyZ69II7j1go',
    appId: '1:1019228006325:web:bdf097c14cfe9db49d9bfc',
    messagingSenderId: '1019228006325',
    projectId: 'temu-recipe',
    authDomain: 'temu-recipe.firebaseapp.com',
    storageBucket: 'temu-recipe.firebasestorage.app',
  );
}
